import { getAllArticles } from "@/data/articleData";
const all: any[] = getAllArticles() as any;
const isTTC = (a: any) => JSON.stringify(a.journey ?? a.journeys ?? "").toLowerCase().includes("trying");
const ttc = all.filter(isTTC);
console.log("total", all.length, "ttc", ttc.length);
const labelOnly = ttc.filter((a) => (a.sources||[]).length && (a.sources||[]).every((s:any)=>typeof s==="string"));
console.log("labelOnly", labelOnly.length);
labelOnly.forEach((a)=>console.log("-", a.slug, "|", JSON.stringify(a.sources)));
const map = new Map<string,any>();
all.forEach((a)=>(a.sources||[]).forEach((s:any)=>{ if(typeof s==="object") map.set(`${s.label}|${s.publisher||""}|${s.year||""}`, s.url); }));
console.log("STRUCTURED", map.size);
[...map.entries()].sort().forEach(([k,v])=>console.log("  *", k, "=>", v));
