# Generates C1_8_ownership_matrix.sql from a per-relationship spec (plan section I, all 13 relationships).
# Rollback-only harness: one explicit transaction, savepoint around every statement that must be rejected,
# explicit ROLLBACK at the end so no binding, row or updated_at change persists. No bypass of any kind.
A = "b09cd318-8f3e-4853-8d97-fc10267b3d69"
B = "820f49d1-2ebc-4bf1-a1e5-f6d32491bbbb"
C = "6e65487d-ddb0-43b6-a623-fb24b5318dab"
EA1 = "00000000-0000-4c10-8000-00000000ea01"
EB1 = "00000000-0000-4c10-8000-00000000eb01"
NEW = lambda n: f"00000000-0000-4c10-8000-00000000c8{n:02x}"
WK = lambda s: 30 + (s % 10)  # weeks 31..36, inside every week CHECK and clear of the legacy weeks 12 and 30

# table -> (legacy A row id, insert column list, value-builder(user, episode_expr, seq) -> values tuple string)
def q(s): return "'" + s + "'"
def vals_reflections(u, e, s): return f"({q(NEW(s))}, {q(u)}, {WK(s)}, 'C1 synthetic c1.8', {e})"
def vals_week_photos(u, e, s): return f"({q(NEW(s))}, {q(u)}, {WK(s)}, '{u}/{WK(s)}.jpg', {e})"
def vals_week_media(u, e, s): return f"({q(NEW(s))}, {q(u)}, {WK(s)}, 'video', 'video/mp4', '{u}/{WK(s)}.mp4', 1024, {e})"
def vals_appt(u, e, s): return f"({q(NEW(s))}, {q(u)}, {WK(s)}, {e})"
def vals_symptom(u, e, s): return f"({q(NEW(s))}, {q(u)}, 'C1 synthetic symptom', {e})"
def vals_movement(u, e, s): return f"({q(NEW(s))}, {q(u)}, 'C1 synthetic pattern', {e})"
def vals_birth_plan(u, e, s): return f"({q(NEW(s))}, {q(u)}, {e})"
def vals_bag(u, e, s): return f"({q(NEW(s))}, {q(u)}, 'parent', 'c1_c8_item_{s}', 'C1 synthetic item', {e})"
def vals_midwife(u, e, s): return f"({q(NEW(s))}, {q(u)}, 'other', 'C1 synthetic question?', {e})"
def vals_session(u, e, s): return f"({q(NEW(s))}, {q(u)}, timestamptz '2026-10-02T20:00:00Z', {e})"
def vals_event(u, e, s): return f"({q(NEW(s))}, {q(u)}, '00000000-0000-4c10-8000-00000000a110', timestamptz '2026-10-01T20:00:00Z' + {s} * interval '1 second', {e})"
def vals_baby(u, e, s): return f"({q(NEW(s))}, {q(u)}, 'C1 synthetic baby', date '2026-09-20', {s % 4 + 1}, {'true' if s % 4 == 0 else 'false'}, {e})"

SPEC = [
    # name, legacy A row, columns, builder, notes
    ("reflections", "00000000-0000-4c10-8000-00000000a101", "(id, user_id, week, content, pregnancy_episode_id)", vals_reflections, ""),
    ("week_photos", "00000000-0000-4c10-8000-00000000a102", "(id, user_id, week, storage_path, pregnancy_episode_id)", vals_week_photos, ""),
    ("week_media_memories", "00000000-0000-4c10-8000-00000000a103", "(id, user_id, week, media_type, mime_type, storage_path, file_size_bytes, pregnancy_episode_id)", vals_week_media, ""),
    ("pregnancy_appointments", "00000000-0000-4c10-8000-00000000a104", "(id, user_id, week, pregnancy_episode_id)", vals_appt, ""),
    ("pregnancy_symptom_notes", "00000000-0000-4c10-8000-00000000a105", "(id, user_id, symptom_label, pregnancy_episode_id)", vals_symptom, ""),
    ("baby_movement_notes", "00000000-0000-4c10-8000-00000000a106", "(id, user_id, pattern_label, pregnancy_episode_id)", vals_movement, ""),
    ("birth_plans", "00000000-0000-4c10-8000-00000000a107", "(id, user_id, pregnancy_episode_id)", vals_birth_plan, "UNIQUE (user_id): A already has a birth plan, so the insert cases use user B (B row -> E-B1 accepted; B row -> E-A1 rejected); the update cases use A legacy row a107."),
    ("hospital_bag_items", "00000000-0000-4c10-8000-00000000a108", "(id, user_id, category, item_key, label, pregnancy_episode_id)", vals_bag, ""),
    ("midwife_questions", "00000000-0000-4c10-8000-00000000a109", "(id, user_id, category, question, pregnancy_episode_id)", vals_midwife, ""),
    ("contraction_sessions", "00000000-0000-4c10-8000-00000000a110", "(id, user_id, started_at, pregnancy_episode_id)", vals_session, ""),
    ("contraction_events", "00000000-0000-4c10-8000-00000000a111", "(id, user_id, session_id, started_at, pregnancy_episode_id)", vals_event, "New events are attached to the existing A session a110, so the pre-existing (session_id, user_id) FK is satisfied and only the ownership FK can reject."),
    ("babies", None, "(id, user_id, name, date_of_birth, birth_order, is_primary, pregnancy_episode_id)", vals_baby, "A has no legacy baby: the legacy-row update cases use B babies b001/b002 with B episode E-B1 (same user) and A episode E-A1 (cross user)."),
]

out = []
w = out.append
w("-- 41B.1A-C1 C1.8 — Ownership integrity matrix (plan section I, all 13 relationships). Generated by gen_c1_8.py.")
w("-- Rollback-only: one explicit transaction, SAVEPOINT around every statement expected to be rejected, final ROLLBACK.")
w("-- No FK/RLS/trigger bypass. Synthetic users A/B/C and episodes E-A1 (A) / E-B1 (B) only.")
w("\\set ON_ERROR_STOP 0")
w("\\set VERBOSITY verbose")
w("\\pset footer off")
w("\\echo === C1.8 start")
w("select now() as started_at, current_user, (select project_ref || ' / ' || run_label from public.c1_rehearsal_marker) as marker;")
w("BEGIN;")
w("SET LOCAL lock_timeout = '5s';")
w("\\echo === episodes present (E-B1 exists, so a single-column FK on episode id alone would pass; only the composite (episode, user) key can reject)")
w("select id, user_id, status from public.pregnancy_episodes order by id;")
w("select conname, condeferrable, condeferred from pg_constraint where contype='f' and confrelid='public.pregnancy_episodes'::regclass order by conname;")

sp = 0
def case(tag, table, expect, sql, after_select=None):
    """expect: 'OK' or 'FK'. Emits a marker, the statement (with savepoint if FK), and an optional verification select."""
    global sp
    w(f"\\echo ### CASE {table}|{tag}|{expect}")
    if expect == "FK":
        sp += 1
        w(f"savepoint s{sp};")
        w(sql)
        w(f"rollback to savepoint s{sp};")
    else:
        w(sql)
    if after_select:
        w(after_select)

seq = 0
for name, legacy, cols, build, note in SPEC:
    seq += 10
    fk = f"{name}_pregnancy_episode_owner_fkey"
    w(f"\\echo === relationship {name} ({fk}){' — ' + note if note else ''}")
    link = "pregnancy_episode_id"
    ins = lambda u, e, s: f"insert into public.{name} {cols} values {build(u, e, s)};"
    sel = lambda rid: f"select id, user_id, {link} from public.{name} where id = '{rid}';"
    if name == "birth_plans":
        u_ins, e_same, e_cross = B, EB1, EA1
    else:
        u_ins, e_same, e_cross = A, EA1, EB1
    # birth_plans has UNIQUE (user_id): an accepted insert must be deleted again (after its read-back) so the next insert case is not blocked by the unique key
    tidy = (lambda rid: f" delete from public.birth_plans where id = '{rid}';") if name == "birth_plans" else (lambda rid: "")
    # I-1 same user insert -> own episode (accepted), read back
    case("I1 same-user insert -> own episode", name, "OK", ins(u_ins, q(e_same), seq + 1), sel(NEW(seq + 1)) + tidy(NEW(seq + 1)))
    # I-2 cross user insert -> other user's episode (rejected)
    case("I2 cross-user insert -> other-user episode", name, "FK", ins(u_ins, q(e_cross), seq + 2), f"select count(*) as residue from public.{name} where id = '{NEW(seq + 2)}';")
    # I-3 NULL link accepted
    case("I3 insert with NULL link", name, "OK", ins(u_ins, "NULL", seq + 3), sel(NEW(seq + 3)) + tidy(NEW(seq + 3)))
    if name == "babies":
        # legacy rows belong to B: I-4 cross user update (B row -> E-A1), I-5 same user update (B row -> E-B1, then NULL)
        case("I4 update legacy NULL-link row -> other-user episode (B b002 -> E-A1)", name, "FK",
             f"update public.babies set pregnancy_episode_id = '{EA1}' where id = '00000000-0000-4c10-8000-00000000b002';",
             sel("00000000-0000-4c10-8000-00000000b002"))
        case("I5a update legacy row -> own episode (B b001 -> E-B1)", name, "OK",
             f"update public.babies set pregnancy_episode_id = '{EB1}' where id = '00000000-0000-4c10-8000-00000000b001';",
             sel("00000000-0000-4c10-8000-00000000b001"))
        case("I5b update back to NULL (B b001)", name, "OK",
             "update public.babies set pregnancy_episode_id = NULL where id = '00000000-0000-4c10-8000-00000000b001';",
             sel("00000000-0000-4c10-8000-00000000b001"))
    else:
        case("I4 update legacy NULL-link A row -> E-B1", name, "FK",
             f"update public.{name} set {link} = '{EB1}' where id = '{legacy}';", sel(legacy))
        case("I5a update legacy A row -> E-A1", name, "OK",
             f"update public.{name} set {link} = '{EA1}' where id = '{legacy}';", sel(legacy))
        case("I5b update back to NULL", name, "OK",
             f"update public.{name} set {link} = NULL where id = '{legacy}';", sel(legacy))
    # I-6 composite mismatch: row user_id = A (or B for birth_plans) with the other user's existing episode id
    case("I6 composite mismatch insert (own user_id + other-user existing episode id)", name, "FK", ins(u_ins, q(e_cross), seq + 6),
         f"select count(*) as residue from public.{name} where id = '{NEW(seq + 6)}';")
    if name == "contraction_events":
        # I-7 session-consistent binding accepted; event/session mismatch not constrained in 41B.1A (recorded)
        case("I7a bind session a110 -> E-A1", name, "OK",
             f"update public.contraction_sessions set pregnancy_episode_id = '{EA1}' where id = '00000000-0000-4c10-8000-00000000a110';",
             "select id, pregnancy_episode_id from public.contraction_sessions where id = '00000000-0000-4c10-8000-00000000a110';")
        case("I7b bind events a111,a112 -> E-A1 (consistent with session)", name, "OK",
             f"update public.contraction_events set pregnancy_episode_id = '{EA1}' where id in ('00000000-0000-4c10-8000-00000000a111','00000000-0000-4c10-8000-00000000a112');",
             "select id, session_id, pregnancy_episode_id from public.contraction_events where session_id = '00000000-0000-4c10-8000-00000000a110' order by id;")
        case("I7c mismatch: event a112 -> NULL while session stays E-A1 (not constrained in 41B.1A; recorded for the 41B.1C trigger)", name, "OK",
             "update public.contraction_events set pregnancy_episode_id = NULL where id = '00000000-0000-4c10-8000-00000000a112';",
             "select e.id, e.pregnancy_episode_id as event_episode, s.pregnancy_episode_id as session_episode from public.contraction_events e join public.contraction_sessions s on s.id = e.session_id where e.session_id = '00000000-0000-4c10-8000-00000000a110' order by e.id;")
        case("I7d reset session and events to NULL", name, "OK",
             "update public.contraction_events set pregnancy_episode_id = NULL where session_id = '00000000-0000-4c10-8000-00000000a110'; update public.contraction_sessions set pregnancy_episode_id = NULL where id = '00000000-0000-4c10-8000-00000000a110';",
             "select (select count(*) from public.contraction_events where pregnancy_episode_id is not null) as events_linked, (select count(*) from public.contraction_sessions where pregnancy_episode_id is not null) as sessions_linked;")

# journeys pointer (one row per user: updates only)
w("\\echo === relationship journeys (journeys_current_pregnancy_episode_owner_fkey) — one row per user, so every case is an update of current_pregnancy_episode_id")
jsel = lambda u: f"select user_id, lifecycle, current_pregnancy_episode_id from public.journeys where user_id = '{u}';"
case("I1/I5a same-user: A pointer -> E-A1", "journeys", "OK", f"update public.journeys set current_pregnancy_episode_id = '{EA1}' where user_id = '{A}';", jsel(A))
case("I2/I6 cross-user: A pointer -> E-B1 (composite mismatch, E-B1 exists)", "journeys", "FK", f"update public.journeys set current_pregnancy_episode_id = '{EB1}' where user_id = '{A}';", jsel(A))
case("I5b back to NULL: A pointer -> NULL", "journeys", "OK", f"update public.journeys set current_pregnancy_episode_id = NULL where user_id = '{A}';", jsel(A))
case("I4 update legacy NULL-pointer row of another user: C pointer -> E-A1", "journeys", "FK", f"update public.journeys set current_pregnancy_episode_id = '{EA1}' where user_id = '{C}';", jsel(C))
case("I4b B pointer -> E-A1 (cross-user)", "journeys", "FK", f"update public.journeys set current_pregnancy_episode_id = '{EA1}' where user_id = '{B}';", jsel(B))
case("I1b B pointer -> E-B1 (same-user) then NULL", "journeys", "OK", f"update public.journeys set current_pregnancy_episode_id = '{EB1}' where user_id = '{B}'; update public.journeys set current_pregnancy_episode_id = NULL where user_id = '{B}';", jsel(B))
case("I3 NULL pointer accepted (explicit)", "journeys", "OK", f"update public.journeys set current_pregnancy_episode_id = NULL where user_id = '{A}';", "select user_id, lifecycle, current_pregnancy_episode_id from public.journeys order by lifecycle;")

w("\\echo === in-transaction summary before rollback")
w("select (select count(*) from public.pregnancy_episodes) as episode_rows, (select count(*) from pg_constraint where contype='f' and confrelid='public.pregnancy_episodes'::regclass and convalidated) as validated;")
w("\\echo === ROLLBACK (rollback-only harness: nothing from this matrix persists)")
w("ROLLBACK;")
w("\\echo === post-state (autocommit, new snapshot)")
w("select now() as finished_at, (select count(*) from public.pregnancy_episodes) as episode_rows,"
  " (select count(*) from public.journeys where current_pregnancy_episode_id is not null) as pointer_non_null,"
  " ((select count(*) from public.reflections where pregnancy_episode_id is not null)+(select count(*) from public.week_photos where pregnancy_episode_id is not null)+(select count(*) from public.week_media_memories where pregnancy_episode_id is not null)+(select count(*) from public.pregnancy_appointments where pregnancy_episode_id is not null)+(select count(*) from public.pregnancy_symptom_notes where pregnancy_episode_id is not null)+(select count(*) from public.baby_movement_notes where pregnancy_episode_id is not null)+(select count(*) from public.birth_plans where pregnancy_episode_id is not null)+(select count(*) from public.hospital_bag_items where pregnancy_episode_id is not null)+(select count(*) from public.midwife_questions where pregnancy_episode_id is not null)+(select count(*) from public.contraction_sessions where pregnancy_episode_id is not null)+(select count(*) from public.contraction_events where pregnancy_episode_id is not null)+(select count(*) from public.babies where pregnancy_episode_id is not null)) as links_non_null,"
  " ((select count(*) from public.journeys)+(select count(*) from public.pregnancy_journeys)+(select count(*) from public.first_year_journeys)+(select count(*) from public.ttc_journeys)+(select count(*) from public.babies)+(select count(*) from public.reflections)+(select count(*) from public.week_photos)+(select count(*) from public.week_media_memories)+(select count(*) from public.pregnancy_appointments)+(select count(*) from public.pregnancy_symptom_notes)+(select count(*) from public.baby_movement_notes)+(select count(*) from public.birth_plans)+(select count(*) from public.hospital_bag_items)+(select count(*) from public.midwife_questions)+(select count(*) from public.contraction_sessions)+(select count(*) from public.contraction_events)) as legacy_fixture_rows,"
  " (select count(*) from public.reflections where id::text like '00000000-0000-4c10-8000-00000000c8%') + (select count(*) from public.babies where id::text like '00000000-0000-4c10-8000-00000000c8%') as c8_residue_sample,"
  " (select count(*) from pg_constraint where contype='f' and confrelid='public.pregnancy_episodes'::regclass and convalidated) as validated,"
  " (select count(*) from supabase_migrations.schema_migrations) as history,"
  " (select max(updated_at) from public.journeys) as journeys_max_updated_at;")
w("\\echo === C1.8 end")
open(r"C:\Users\Administrator\.c1\C1_8_ownership_matrix.sql", "w", encoding="utf-8", newline="\n").write("\n".join(out) + "\n")
print("cases:", sum(1 for l in out if l.startswith("\\echo ### CASE")), "savepoints:", sp)
