-- 41B.1A-C1 C1.10 — Episode CHECK semantics (plan stage C1.10, exact list, plus equivalent boundary proofs). Generated by gen_c1_10.py.
-- Every case in its own SAVEPOINT (accepted rows read back then rolled back), one explicit transaction, final ROLLBACK. No bypass.
-- Inserts use synthetic user C (no episode) so the one-open unique index cannot fire; only the constraint under test can reject.
\set ON_ERROR_STOP 0
\set VERBOSITY verbose
\pset footer off
\echo === C1.10 start
select now() as started_at, current_user, (select project_ref || ' / ' || run_label from public.c1_rehearsal_marker) as marker;
BEGIN;
SET LOCAL lock_timeout = '5s';
\echo === live CHECK definitions and nullability (read-only)
select conname, pg_get_constraintdef(oid) as def, convalidated from pg_constraint where conrelid = 'public.pregnancy_episodes'::regclass and contype = 'c' order by conname;
select column_name, is_nullable from information_schema.columns where table_schema = 'public' and table_name = 'pregnancy_episodes' and column_name in ('lmp_date','due_date','status','ended_at','expected_count') order by ordinal_position;
select count(*) as c_episodes_before from public.pregnancy_episodes where user_id = '6e65487d-ddb0-43b6-a623-fb24b5318dab';
\echo ### CASE C10-01|dates|due_date = lmp_date (plan)|lmp=date '2026-09-01' due=date '2026-09-01' status=active ended_at=NULL expected_count=1|CK:pregnancy_episodes_dates_check|plan
savepoint sp1;
insert into public.pregnancy_episodes (id, user_id, lmp_date, due_date, status, ended_at, expected_count) values ('00000000-0000-4c10-8000-00000000ca01', '6e65487d-ddb0-43b6-a623-fb24b5318dab', date '2026-09-01', date '2026-09-01', 'active', NULL, 1);
rollback to savepoint sp1;
select count(*) as residue from public.pregnancy_episodes where id = '00000000-0000-4c10-8000-00000000ca01';
\echo ### CASE C10-02|dates|due_date = lmp_date + 300 (plan)|lmp=date '2026-09-01' due=date '2026-09-01' + 300 status=active ended_at=NULL expected_count=1|OK|plan
savepoint sp2;
insert into public.pregnancy_episodes (id, user_id, lmp_date, due_date, status, ended_at, expected_count) values ('00000000-0000-4c10-8000-00000000ca02', '6e65487d-ddb0-43b6-a623-fb24b5318dab', date '2026-09-01', date '2026-09-01' + 300, 'active', NULL, 1);
select id, user_id, lmp_date, due_date, (due_date - lmp_date) as due_minus_lmp, status, ended_at, expected_count, removed_at from public.pregnancy_episodes where id = '00000000-0000-4c10-8000-00000000ca02';
rollback to savepoint sp2;
select count(*) as residue from public.pregnancy_episodes where id = '00000000-0000-4c10-8000-00000000ca02';
\echo ### CASE C10-03|dates|due_date = lmp_date + 301 (plan)|lmp=date '2026-09-01' due=date '2026-09-01' + 301 status=active ended_at=NULL expected_count=1|CK:pregnancy_episodes_dates_check|plan
savepoint sp3;
insert into public.pregnancy_episodes (id, user_id, lmp_date, due_date, status, ended_at, expected_count) values ('00000000-0000-4c10-8000-00000000ca03', '6e65487d-ddb0-43b6-a623-fb24b5318dab', date '2026-09-01', date '2026-09-01' + 301, 'active', NULL, 1);
rollback to savepoint sp3;
select count(*) as residue from public.pregnancy_episodes where id = '00000000-0000-4c10-8000-00000000ca03';
\echo ### CASE C10-04|dates|due_date = lmp_date + 1 (boundary equivalent)|lmp=date '2026-09-01' due=date '2026-09-01' + 1 status=active ended_at=NULL expected_count=1|OK|equivalent
savepoint sp4;
insert into public.pregnancy_episodes (id, user_id, lmp_date, due_date, status, ended_at, expected_count) values ('00000000-0000-4c10-8000-00000000ca04', '6e65487d-ddb0-43b6-a623-fb24b5318dab', date '2026-09-01', date '2026-09-01' + 1, 'active', NULL, 1);
select id, user_id, lmp_date, due_date, (due_date - lmp_date) as due_minus_lmp, status, ended_at, expected_count, removed_at from public.pregnancy_episodes where id = '00000000-0000-4c10-8000-00000000ca04';
rollback to savepoint sp4;
select count(*) as residue from public.pregnancy_episodes where id = '00000000-0000-4c10-8000-00000000ca04';
\echo ### CASE C10-05|dates|due_date = lmp_date - 1 (boundary equivalent)|lmp=date '2026-09-01' due=date '2026-09-01' - 1 status=active ended_at=NULL expected_count=1|CK:pregnancy_episodes_dates_check|equivalent
savepoint sp5;
insert into public.pregnancy_episodes (id, user_id, lmp_date, due_date, status, ended_at, expected_count) values ('00000000-0000-4c10-8000-00000000ca05', '6e65487d-ddb0-43b6-a623-fb24b5318dab', date '2026-09-01', date '2026-09-01' - 1, 'active', NULL, 1);
rollback to savepoint sp5;
select count(*) as residue from public.pregnancy_episodes where id = '00000000-0000-4c10-8000-00000000ca05';
\echo ### CASE C10-06|not_null|lmp_date NULL (plan)|lmp=NULL due=date '2027-06-08' status=active ended_at=NULL expected_count=1|NN:lmp_date|plan
savepoint sp6;
insert into public.pregnancy_episodes (id, user_id, lmp_date, due_date, status, ended_at, expected_count) values ('00000000-0000-4c10-8000-00000000ca06', '6e65487d-ddb0-43b6-a623-fb24b5318dab', NULL, date '2027-06-08', 'active', NULL, 1);
rollback to savepoint sp6;
select count(*) as residue from public.pregnancy_episodes where id = '00000000-0000-4c10-8000-00000000ca06';
\echo ### CASE C10-07|not_null|due_date NULL (equivalent)|lmp=date '2026-09-01' due=NULL status=active ended_at=NULL expected_count=1|NN:due_date|equivalent
savepoint sp7;
insert into public.pregnancy_episodes (id, user_id, lmp_date, due_date, status, ended_at, expected_count) values ('00000000-0000-4c10-8000-00000000ca07', '6e65487d-ddb0-43b6-a623-fb24b5318dab', date '2026-09-01', NULL, 'active', NULL, 1);
rollback to savepoint sp7;
select count(*) as residue from public.pregnancy_episodes where id = '00000000-0000-4c10-8000-00000000ca07';
\echo ### CASE C10-08|expected_count|expected_count 0 (plan)|lmp=date '2026-09-01' due=date '2027-06-08' status=active ended_at=NULL expected_count=0|CK:pregnancy_episodes_expected_count_check|plan
savepoint sp8;
insert into public.pregnancy_episodes (id, user_id, lmp_date, due_date, status, ended_at, expected_count) values ('00000000-0000-4c10-8000-00000000ca08', '6e65487d-ddb0-43b6-a623-fb24b5318dab', date '2026-09-01', date '2027-06-08', 'active', NULL, 0);
rollback to savepoint sp8;
select count(*) as residue from public.pregnancy_episodes where id = '00000000-0000-4c10-8000-00000000ca08';
\echo ### CASE C10-09|expected_count|expected_count 1 (plan)|lmp=date '2026-09-01' due=date '2027-06-08' status=active ended_at=NULL expected_count=1|OK|plan
savepoint sp9;
insert into public.pregnancy_episodes (id, user_id, lmp_date, due_date, status, ended_at, expected_count) values ('00000000-0000-4c10-8000-00000000ca09', '6e65487d-ddb0-43b6-a623-fb24b5318dab', date '2026-09-01', date '2027-06-08', 'active', NULL, 1);
select id, user_id, lmp_date, due_date, (due_date - lmp_date) as due_minus_lmp, status, ended_at, expected_count, removed_at from public.pregnancy_episodes where id = '00000000-0000-4c10-8000-00000000ca09';
rollback to savepoint sp9;
select count(*) as residue from public.pregnancy_episodes where id = '00000000-0000-4c10-8000-00000000ca09';
\echo ### CASE C10-10|expected_count|expected_count 4 (plan)|lmp=date '2026-09-01' due=date '2027-06-08' status=active ended_at=NULL expected_count=4|OK|plan
savepoint sp10;
insert into public.pregnancy_episodes (id, user_id, lmp_date, due_date, status, ended_at, expected_count) values ('00000000-0000-4c10-8000-00000000ca0a', '6e65487d-ddb0-43b6-a623-fb24b5318dab', date '2026-09-01', date '2027-06-08', 'active', NULL, 4);
select id, user_id, lmp_date, due_date, (due_date - lmp_date) as due_minus_lmp, status, ended_at, expected_count, removed_at from public.pregnancy_episodes where id = '00000000-0000-4c10-8000-00000000ca0a';
rollback to savepoint sp10;
select count(*) as residue from public.pregnancy_episodes where id = '00000000-0000-4c10-8000-00000000ca0a';
\echo ### CASE C10-11|expected_count|expected_count 5 (plan)|lmp=date '2026-09-01' due=date '2027-06-08' status=active ended_at=NULL expected_count=5|CK:pregnancy_episodes_expected_count_check|plan
savepoint sp11;
insert into public.pregnancy_episodes (id, user_id, lmp_date, due_date, status, ended_at, expected_count) values ('00000000-0000-4c10-8000-00000000ca0b', '6e65487d-ddb0-43b6-a623-fb24b5318dab', date '2026-09-01', date '2027-06-08', 'active', NULL, 5);
rollback to savepoint sp11;
select count(*) as residue from public.pregnancy_episodes where id = '00000000-0000-4c10-8000-00000000ca0b';
\echo ### CASE C10-12|expected_count|expected_count NULL (plan)|lmp=date '2026-09-01' due=date '2027-06-08' status=active ended_at=NULL expected_count=NULL|OK|plan
savepoint sp12;
insert into public.pregnancy_episodes (id, user_id, lmp_date, due_date, status, ended_at, expected_count) values ('00000000-0000-4c10-8000-00000000ca0c', '6e65487d-ddb0-43b6-a623-fb24b5318dab', date '2026-09-01', date '2027-06-08', 'active', NULL, NULL);
select id, user_id, lmp_date, due_date, (due_date - lmp_date) as due_minus_lmp, status, ended_at, expected_count, removed_at from public.pregnancy_episodes where id = '00000000-0000-4c10-8000-00000000ca0c';
rollback to savepoint sp12;
select count(*) as residue from public.pregnancy_episodes where id = '00000000-0000-4c10-8000-00000000ca0c';
\echo ### CASE C10-13|expected_count|expected_count 2 (equivalent)|lmp=date '2026-09-01' due=date '2027-06-08' status=active ended_at=NULL expected_count=2|OK|equivalent
savepoint sp13;
insert into public.pregnancy_episodes (id, user_id, lmp_date, due_date, status, ended_at, expected_count) values ('00000000-0000-4c10-8000-00000000ca0d', '6e65487d-ddb0-43b6-a623-fb24b5318dab', date '2026-09-01', date '2027-06-08', 'active', NULL, 2);
select id, user_id, lmp_date, due_date, (due_date - lmp_date) as due_minus_lmp, status, ended_at, expected_count, removed_at from public.pregnancy_episodes where id = '00000000-0000-4c10-8000-00000000ca0d';
rollback to savepoint sp13;
select count(*) as residue from public.pregnancy_episodes where id = '00000000-0000-4c10-8000-00000000ca0d';
\echo ### CASE C10-14|expected_count|expected_count 3 (equivalent)|lmp=date '2026-09-01' due=date '2027-06-08' status=active ended_at=NULL expected_count=3|OK|equivalent
savepoint sp14;
insert into public.pregnancy_episodes (id, user_id, lmp_date, due_date, status, ended_at, expected_count) values ('00000000-0000-4c10-8000-00000000ca0e', '6e65487d-ddb0-43b6-a623-fb24b5318dab', date '2026-09-01', date '2027-06-08', 'active', NULL, 3);
select id, user_id, lmp_date, due_date, (due_date - lmp_date) as due_minus_lmp, status, ended_at, expected_count, removed_at from public.pregnancy_episodes where id = '00000000-0000-4c10-8000-00000000ca0e';
rollback to savepoint sp14;
select count(*) as residue from public.pregnancy_episodes where id = '00000000-0000-4c10-8000-00000000ca0e';
\echo ### CASE C10-15|expected_count|expected_count -1 (equivalent)|lmp=date '2026-09-01' due=date '2027-06-08' status=active ended_at=NULL expected_count=-1|CK:pregnancy_episodes_expected_count_check|equivalent
savepoint sp15;
insert into public.pregnancy_episodes (id, user_id, lmp_date, due_date, status, ended_at, expected_count) values ('00000000-0000-4c10-8000-00000000ca0f', '6e65487d-ddb0-43b6-a623-fb24b5318dab', date '2026-09-01', date '2027-06-08', 'active', NULL, -1);
rollback to savepoint sp15;
select count(*) as residue from public.pregnancy_episodes where id = '00000000-0000-4c10-8000-00000000ca0f';
\echo ### CASE C10-16|status_ended_at|active + ended_at set (plan)|lmp=date '2026-09-01' due=date '2027-06-08' status=active ended_at=timestamptz '2027-06-01T10:00:00Z' expected_count=1|CK:pregnancy_episodes_ended_at_status_check|plan
savepoint sp16;
insert into public.pregnancy_episodes (id, user_id, lmp_date, due_date, status, ended_at, expected_count) values ('00000000-0000-4c10-8000-00000000ca10', '6e65487d-ddb0-43b6-a623-fb24b5318dab', date '2026-09-01', date '2027-06-08', 'active', timestamptz '2027-06-01T10:00:00Z', 1);
rollback to savepoint sp16;
select count(*) as residue from public.pregnancy_episodes where id = '00000000-0000-4c10-8000-00000000ca10';
\echo ### CASE C10-17|status_ended_at|given_birth + ended_at NULL (plan)|lmp=date '2026-09-01' due=date '2027-06-08' status=given_birth ended_at=NULL expected_count=1|CK:pregnancy_episodes_ended_at_status_check|plan
savepoint sp17;
insert into public.pregnancy_episodes (id, user_id, lmp_date, due_date, status, ended_at, expected_count) values ('00000000-0000-4c10-8000-00000000ca11', '6e65487d-ddb0-43b6-a623-fb24b5318dab', date '2026-09-01', date '2027-06-08', 'given_birth', NULL, 1);
rollback to savepoint sp17;
select count(*) as residue from public.pregnancy_episodes where id = '00000000-0000-4c10-8000-00000000ca11';
\echo ### CASE C10-18|status_ended_at|paused + ended_at NULL (plan)|lmp=date '2026-09-01' due=date '2027-06-08' status=paused ended_at=NULL expected_count=1|OK|plan
savepoint sp18;
insert into public.pregnancy_episodes (id, user_id, lmp_date, due_date, status, ended_at, expected_count) values ('00000000-0000-4c10-8000-00000000ca12', '6e65487d-ddb0-43b6-a623-fb24b5318dab', date '2026-09-01', date '2027-06-08', 'paused', NULL, 1);
select id, user_id, lmp_date, due_date, (due_date - lmp_date) as due_minus_lmp, status, ended_at, expected_count, removed_at from public.pregnancy_episodes where id = '00000000-0000-4c10-8000-00000000ca12';
rollback to savepoint sp18;
select count(*) as residue from public.pregnancy_episodes where id = '00000000-0000-4c10-8000-00000000ca12';
\echo ### CASE C10-19|status_ended_at|pregnancy_loss + ended_at set (plan)|lmp=date '2026-09-01' due=date '2027-06-08' status=pregnancy_loss ended_at=timestamptz '2027-06-01T10:00:00Z' expected_count=1|OK|plan
savepoint sp19;
insert into public.pregnancy_episodes (id, user_id, lmp_date, due_date, status, ended_at, expected_count) values ('00000000-0000-4c10-8000-00000000ca13', '6e65487d-ddb0-43b6-a623-fb24b5318dab', date '2026-09-01', date '2027-06-08', 'pregnancy_loss', timestamptz '2027-06-01T10:00:00Z', 1);
select id, user_id, lmp_date, due_date, (due_date - lmp_date) as due_minus_lmp, status, ended_at, expected_count, removed_at from public.pregnancy_episodes where id = '00000000-0000-4c10-8000-00000000ca13';
rollback to savepoint sp19;
select count(*) as residue from public.pregnancy_episodes where id = '00000000-0000-4c10-8000-00000000ca13';
\echo ### CASE C10-20|status_ended_at|active + ended_at NULL (equivalent)|lmp=date '2026-09-01' due=date '2027-06-08' status=active ended_at=NULL expected_count=1|OK|equivalent
savepoint sp20;
insert into public.pregnancy_episodes (id, user_id, lmp_date, due_date, status, ended_at, expected_count) values ('00000000-0000-4c10-8000-00000000ca14', '6e65487d-ddb0-43b6-a623-fb24b5318dab', date '2026-09-01', date '2027-06-08', 'active', NULL, 1);
select id, user_id, lmp_date, due_date, (due_date - lmp_date) as due_minus_lmp, status, ended_at, expected_count, removed_at from public.pregnancy_episodes where id = '00000000-0000-4c10-8000-00000000ca14';
rollback to savepoint sp20;
select count(*) as residue from public.pregnancy_episodes where id = '00000000-0000-4c10-8000-00000000ca14';
\echo ### CASE C10-21|status_ended_at|paused + ended_at set (equivalent)|lmp=date '2026-09-01' due=date '2027-06-08' status=paused ended_at=timestamptz '2027-06-01T10:00:00Z' expected_count=1|CK:pregnancy_episodes_ended_at_status_check|equivalent
savepoint sp21;
insert into public.pregnancy_episodes (id, user_id, lmp_date, due_date, status, ended_at, expected_count) values ('00000000-0000-4c10-8000-00000000ca15', '6e65487d-ddb0-43b6-a623-fb24b5318dab', date '2026-09-01', date '2027-06-08', 'paused', timestamptz '2027-06-01T10:00:00Z', 1);
rollback to savepoint sp21;
select count(*) as residue from public.pregnancy_episodes where id = '00000000-0000-4c10-8000-00000000ca15';
\echo ### CASE C10-22|status_ended_at|given_birth + ended_at set (equivalent)|lmp=date '2026-09-01' due=date '2027-06-08' status=given_birth ended_at=timestamptz '2027-06-01T10:00:00Z' expected_count=1|OK|equivalent
savepoint sp22;
insert into public.pregnancy_episodes (id, user_id, lmp_date, due_date, status, ended_at, expected_count) values ('00000000-0000-4c10-8000-00000000ca16', '6e65487d-ddb0-43b6-a623-fb24b5318dab', date '2026-09-01', date '2027-06-08', 'given_birth', timestamptz '2027-06-01T10:00:00Z', 1);
select id, user_id, lmp_date, due_date, (due_date - lmp_date) as due_minus_lmp, status, ended_at, expected_count, removed_at from public.pregnancy_episodes where id = '00000000-0000-4c10-8000-00000000ca16';
rollback to savepoint sp22;
select count(*) as residue from public.pregnancy_episodes where id = '00000000-0000-4c10-8000-00000000ca16';
\echo ### CASE C10-23|status_ended_at|no_longer_pregnant + ended_at set (equivalent)|lmp=date '2026-09-01' due=date '2027-06-08' status=no_longer_pregnant ended_at=timestamptz '2027-06-01T10:00:00Z' expected_count=1|OK|equivalent
savepoint sp23;
insert into public.pregnancy_episodes (id, user_id, lmp_date, due_date, status, ended_at, expected_count) values ('00000000-0000-4c10-8000-00000000ca17', '6e65487d-ddb0-43b6-a623-fb24b5318dab', date '2026-09-01', date '2027-06-08', 'no_longer_pregnant', timestamptz '2027-06-01T10:00:00Z', 1);
select id, user_id, lmp_date, due_date, (due_date - lmp_date) as due_minus_lmp, status, ended_at, expected_count, removed_at from public.pregnancy_episodes where id = '00000000-0000-4c10-8000-00000000ca17';
rollback to savepoint sp23;
select count(*) as residue from public.pregnancy_episodes where id = '00000000-0000-4c10-8000-00000000ca17';
\echo ### CASE C10-24|status_ended_at|no_longer_pregnant + ended_at NULL (equivalent)|lmp=date '2026-09-01' due=date '2027-06-08' status=no_longer_pregnant ended_at=NULL expected_count=1|CK:pregnancy_episodes_ended_at_status_check|equivalent
savepoint sp24;
insert into public.pregnancy_episodes (id, user_id, lmp_date, due_date, status, ended_at, expected_count) values ('00000000-0000-4c10-8000-00000000ca18', '6e65487d-ddb0-43b6-a623-fb24b5318dab', date '2026-09-01', date '2027-06-08', 'no_longer_pregnant', NULL, 1);
rollback to savepoint sp24;
select count(*) as residue from public.pregnancy_episodes where id = '00000000-0000-4c10-8000-00000000ca18';
\echo ### CASE C10-25|status_ended_at|pregnancy_loss + ended_at NULL (equivalent)|lmp=date '2026-09-01' due=date '2027-06-08' status=pregnancy_loss ended_at=NULL expected_count=1|CK:pregnancy_episodes_ended_at_status_check|equivalent
savepoint sp25;
insert into public.pregnancy_episodes (id, user_id, lmp_date, due_date, status, ended_at, expected_count) values ('00000000-0000-4c10-8000-00000000ca19', '6e65487d-ddb0-43b6-a623-fb24b5318dab', date '2026-09-01', date '2027-06-08', 'pregnancy_loss', NULL, 1);
rollback to savepoint sp25;
select count(*) as residue from public.pregnancy_episodes where id = '00000000-0000-4c10-8000-00000000ca19';
\echo === in-transaction summary before rollback
select count(*) as episode_rows, count(*) filter (where user_id = '6e65487d-ddb0-43b6-a623-fb24b5318dab') as c_rows from public.pregnancy_episodes;
\echo === ROLLBACK (rollback-only harness)
ROLLBACK;
\echo === post-state (autocommit, new snapshot)
select now() as finished_at, (select count(*) from public.pregnancy_episodes) as episode_rows, (select count(*) from public.pregnancy_episodes where id::text like '00000000-0000-4c10-8000-00000000ca%') as c10_residue, (select string_agg(id::text || '|' || status::text || '|removed_at=' || coalesce(removed_at::text,'NULL') || '|updated_at=' || updated_at, ' ;; ' order by id) from public.pregnancy_episodes) as episodes, (select count(*) from supabase_migrations.schema_migrations) as history;
\echo === C1.10 end
