# Generates C1_10_check_matrix.sql: plan stage C1.10 cases (exact list) plus equivalent boundary proofs.
# Every case runs inside its own SAVEPOINT (accepted rows are read back, then the savepoint is rolled back), so the
# one-open partial unique index can never fire and only the constraint under test can reject. Final ROLLBACK.
C = "6e65487d-ddb0-43b6-a623-fb24b5318dab"   # user C has no episode, so open-status inserts never collide
A = "b09cd318-8f3e-4853-8d97-fc10267b3d69"
LMP = "date '2026-09-01'"
DUE = "date '2027-06-08'"                   # lmp + 280
ENDED = "timestamptz '2027-06-01T10:00:00Z'"
NEW = lambda n: f"00000000-0000-4c10-8000-00000000ca{n:02x}"

# (id, rule, description, columns dict, expect) expect: OK | CK:<constraint> | NN:<column>
CASES = []
def add(rule, desc, lmp, due, status, ended, expected_count, expect, user=C, plan=True):
    CASES.append(dict(rule=rule, desc=desc, lmp=lmp, due=due, status=status, ended=ended, ec=expected_count, expect=expect, user=user, plan=plan))

# Dates (plan: =lmp rejected; +300 accepted; +301 rejected) + equivalents (+1 accepted; before lmp rejected)
add("dates", "due_date = lmp_date (plan)", LMP, LMP, "active", "NULL", "1", "CK:pregnancy_episodes_dates_check")
add("dates", "due_date = lmp_date + 300 (plan)", LMP, f"{LMP} + 300", "active", "NULL", "1", "OK")
add("dates", "due_date = lmp_date + 301 (plan)", LMP, f"{LMP} + 301", "active", "NULL", "1", "CK:pregnancy_episodes_dates_check")
add("dates", "due_date = lmp_date + 1 (boundary equivalent)", LMP, f"{LMP} + 1", "active", "NULL", "1", "OK", plan=False)
add("dates", "due_date = lmp_date - 1 (boundary equivalent)", LMP, f"{LMP} - 1", "active", "NULL", "1", "CK:pregnancy_episodes_dates_check", plan=False)
# NOT NULL (plan: lmp_date NULL rejected) + equivalent (due_date NULL)
add("not_null", "lmp_date NULL (plan)", "NULL", DUE, "active", "NULL", "1", "NN:lmp_date")
add("not_null", "due_date NULL (equivalent)", LMP, "NULL", "active", "NULL", "1", "NN:due_date", plan=False)
# expected_count (plan: 0 rejected; 1, 4 accepted; 5 rejected; NULL accepted) + equivalents (2, 3 accepted; -1 rejected)
add("expected_count", "expected_count 0 (plan)", LMP, DUE, "active", "NULL", "0", "CK:pregnancy_episodes_expected_count_check")
add("expected_count", "expected_count 1 (plan)", LMP, DUE, "active", "NULL", "1", "OK")
add("expected_count", "expected_count 4 (plan)", LMP, DUE, "active", "NULL", "4", "OK")
add("expected_count", "expected_count 5 (plan)", LMP, DUE, "active", "NULL", "5", "CK:pregnancy_episodes_expected_count_check")
add("expected_count", "expected_count NULL (plan)", LMP, DUE, "active", "NULL", "NULL", "OK")
add("expected_count", "expected_count 2 (equivalent)", LMP, DUE, "active", "NULL", "2", "OK", plan=False)
add("expected_count", "expected_count 3 (equivalent)", LMP, DUE, "active", "NULL", "3", "OK", plan=False)
add("expected_count", "expected_count -1 (equivalent)", LMP, DUE, "active", "NULL", "-1", "CK:pregnancy_episodes_expected_count_check", plan=False)
# status / ended_at (plan: active+set rejected; given_birth+NULL rejected; paused+NULL accepted; pregnancy_loss+set accepted) + full enum coverage
add("status_ended_at", "active + ended_at set (plan)", LMP, DUE, "active", ENDED, "1", "CK:pregnancy_episodes_ended_at_status_check")
add("status_ended_at", "given_birth + ended_at NULL (plan)", LMP, DUE, "given_birth", "NULL", "1", "CK:pregnancy_episodes_ended_at_status_check")
add("status_ended_at", "paused + ended_at NULL (plan)", LMP, DUE, "paused", "NULL", "1", "OK")
add("status_ended_at", "pregnancy_loss + ended_at set (plan)", LMP, DUE, "pregnancy_loss", ENDED, "1", "OK")
add("status_ended_at", "active + ended_at NULL (equivalent)", LMP, DUE, "active", "NULL", "1", "OK", plan=False)
add("status_ended_at", "paused + ended_at set (equivalent)", LMP, DUE, "paused", ENDED, "1", "CK:pregnancy_episodes_ended_at_status_check", plan=False)
add("status_ended_at", "given_birth + ended_at set (equivalent)", LMP, DUE, "given_birth", ENDED, "1", "OK", plan=False)
add("status_ended_at", "no_longer_pregnant + ended_at set (equivalent)", LMP, DUE, "no_longer_pregnant", ENDED, "1", "OK", plan=False)
add("status_ended_at", "no_longer_pregnant + ended_at NULL (equivalent)", LMP, DUE, "no_longer_pregnant", "NULL", "1", "CK:pregnancy_episodes_ended_at_status_check", plan=False)
add("status_ended_at", "pregnancy_loss + ended_at NULL (equivalent)", LMP, DUE, "pregnancy_loss", "NULL", "1", "CK:pregnancy_episodes_ended_at_status_check", plan=False)

out = []
w = out.append
w("-- 41B.1A-C1 C1.10 — Episode CHECK semantics (plan stage C1.10, exact list, plus equivalent boundary proofs). Generated by gen_c1_10.py.")
w("-- Every case in its own SAVEPOINT (accepted rows read back then rolled back), one explicit transaction, final ROLLBACK. No bypass.")
w("-- Inserts use synthetic user C (no episode) so the one-open unique index cannot fire; only the constraint under test can reject.")
w("\\set ON_ERROR_STOP 0")
w("\\set VERBOSITY verbose")
w("\\pset footer off")
w("\\echo === C1.10 start")
w("select now() as started_at, current_user, (select project_ref || ' / ' || run_label from public.c1_rehearsal_marker) as marker;")
w("BEGIN;")
w("SET LOCAL lock_timeout = '5s';")
w("\\echo === live CHECK definitions and nullability (read-only)")
w("select conname, pg_get_constraintdef(oid) as def, convalidated from pg_constraint where conrelid = 'public.pregnancy_episodes'::regclass and contype = 'c' order by conname;")
w("select column_name, is_nullable from information_schema.columns where table_schema = 'public' and table_name = 'pregnancy_episodes' and column_name in ('lmp_date','due_date','status','ended_at','expected_count') order by ordinal_position;")
w("select count(*) as c_episodes_before from public.pregnancy_episodes where user_id = '" + C + "';")
for n, c in enumerate(CASES, 1):
    rid = NEW(n)
    vals = f"lmp={c['lmp']} due={c['due']} status={c['status']} ended_at={c['ended']} expected_count={c['ec']}"
    w(f"\\echo ### CASE C10-{n:02d}|{c['rule']}|{c['desc']}|{vals}|{c['expect']}|{'plan' if c['plan'] else 'equivalent'}")
    w(f"savepoint sp{n};")
    w(f"insert into public.pregnancy_episodes (id, user_id, lmp_date, due_date, status, ended_at, expected_count) values ('{rid}', '{c['user']}', {c['lmp']}, {c['due']}, '{c['status']}', {c['ended']}, {c['ec']});")
    if c["expect"] == "OK":
        w(f"select id, user_id, lmp_date, due_date, (due_date - lmp_date) as due_minus_lmp, status, ended_at, expected_count, removed_at from public.pregnancy_episodes where id = '{rid}';")
    w(f"rollback to savepoint sp{n};")
    w(f"select count(*) as residue from public.pregnancy_episodes where id = '{rid}';")
w("\\echo === in-transaction summary before rollback")
w("select count(*) as episode_rows, count(*) filter (where user_id = '" + C + "') as c_rows from public.pregnancy_episodes;")
w("\\echo === ROLLBACK (rollback-only harness)")
w("ROLLBACK;")
w("\\echo === post-state (autocommit, new snapshot)")
w("select now() as finished_at, (select count(*) from public.pregnancy_episodes) as episode_rows, (select count(*) from public.pregnancy_episodes where id::text like '00000000-0000-4c10-8000-00000000ca%') as c10_residue, (select string_agg(id::text || '|' || status::text || '|removed_at=' || coalesce(removed_at::text,'NULL') || '|updated_at=' || updated_at, ' ;; ' order by id) from public.pregnancy_episodes) as episodes, (select count(*) from supabase_migrations.schema_migrations) as history;")
w("\\echo === C1.10 end")
open(r"C:\Users\Administrator\.c1\C1_10_check_matrix.sql", "w", encoding="utf-8", newline="\n").write("\n".join(out) + "\n")
print("cases:", len(CASES), "plan:", sum(c['plan'] for c in CASES), "equivalent:", sum(not c['plan'] for c in CASES))
