/**
 * Phase 30C — article grounding approval registry (metadata only).
 *
 * This file is NOT part of any AI code path. Nothing here is read by
 * `ai-search`, by any prompt, mode, source-routing rule or answer renderer.
 * It records governance metadata about Start of You articles so that a future,
 * separately gated phase could decide whether an article is even a candidate
 * for grounding.
 *
 * Hard rules:
 *  - No article body, section, prose, takeaway, description, image or media
 *    content may ever be stored here. Metadata only.
 *  - No user-authored content (journal, notes, reflections, logs, media) is
 *    representable in this registry, by design.
 *  - Every article is not approved. No entry may carry
 *    `approvalStatus: "approved"` in this phase.
 *
 * Entries were compiled from the existing article datasets and cross-checked
 * against `src/data/articleInventory.ts` editorial status. Because no article
 * yet carries a sensitivity level, content version, recorded owner or
 * grounding approval record, every live article is
 * `blocked_missing_metadata` and every draft is `blocked_draft`.
 */

import type { ArticleGroundingRecord } from "./articleGroundingTypes";

export const ARTICLE_GROUNDING_REGISTRY: readonly ArticleGroundingRecord[] = [
  { slug: "nausea-in-early-pregnancy", journey: ["pregnancy"], topics: [], editorialStatus: "live", archived: false, deprecated: false, hasSourceList: false, approvalStatus: "blocked_missing_metadata" },
  { slug: "fatigue-in-early-pregnancy", journey: ["pregnancy"], topics: [], editorialStatus: "live", archived: false, deprecated: false, hasSourceList: false, approvalStatus: "blocked_missing_metadata" },
  { slug: "implantation-bleeding", journey: ["pregnancy","trying-to-conceive"], topics: ["body"], editorialStatus: "live", archived: false, deprecated: false, hasSourceList: true, approvalStatus: "blocked_missing_metadata" },
  { slug: "symptoms-stopping-early-pregnancy", journey: ["pregnancy"], topics: [], editorialStatus: "live", archived: false, deprecated: false, hasSourceList: false, approvalStatus: "blocked_missing_metadata" },
  { slug: "complete-guide-morning-sickness", journey: ["pregnancy"], topics: [], editorialStatus: "live", archived: false, deprecated: false, hasSourceList: true, approvalStatus: "blocked_missing_metadata" },
  { slug: "first-trimester-complete-guide", journey: ["pregnancy"], topics: ["body"], editorialStatus: "live", archived: false, deprecated: false, hasSourceList: true, approvalStatus: "blocked_missing_metadata" },
  { slug: "early-pregnancy-symptoms-explained", journey: ["pregnancy"], topics: ["body"], editorialStatus: "live", archived: false, deprecated: false, hasSourceList: true, approvalStatus: "blocked_missing_metadata" },
  { slug: "postpartum-recovery-timeline", journey: ["postpartum"], topics: [], editorialStatus: "live", archived: false, deprecated: false, hasSourceList: true, approvalStatus: "blocked_missing_metadata" },
  { slug: "trying-to-conceive-explained", journey: ["trying-to-conceive"], topics: [], editorialStatus: "live", archived: false, deprecated: false, hasSourceList: true, approvalStatus: "blocked_missing_metadata" },
  { slug: "ivf-timeline-what-to-expect", journey: ["ivf"], topics: [], editorialStatus: "live", archived: false, deprecated: false, hasSourceList: true, approvalStatus: "blocked_missing_metadata" },
  { slug: "baby-sleep-first-year", journey: ["first-year","postpartum"], topics: [], editorialStatus: "live", archived: false, deprecated: false, hasSourceList: true, approvalStatus: "blocked_missing_metadata" },
  { slug: "second-trimester-complete-guide", journey: ["pregnancy"], topics: ["body"], editorialStatus: "live", archived: false, deprecated: false, hasSourceList: true, approvalStatus: "blocked_missing_metadata" },
  { slug: "third-trimester-complete-guide", journey: ["pregnancy"], topics: ["body"], editorialStatus: "live", archived: false, deprecated: false, hasSourceList: true, approvalStatus: "blocked_missing_metadata" },
  { slug: "preparing-for-baby-complete-guide", journey: ["preparing-for-baby","pregnancy"], topics: [], editorialStatus: "live", archived: false, deprecated: false, hasSourceList: true, approvalStatus: "blocked_missing_metadata" },
  { slug: "emotional-wellbeing-pregnancy", journey: ["pregnancy","support"], topics: ["feelings"], editorialStatus: "live", archived: false, deprecated: false, hasSourceList: true, approvalStatus: "blocked_missing_metadata" },
  { slug: "feeding-your-baby-complete-guide", journey: ["postpartum","first-year"], topics: [], editorialStatus: "live", archived: false, deprecated: false, hasSourceList: true, approvalStatus: "blocked_missing_metadata" },
  { slug: "signs-of-ovulation", journey: ["trying-to-conceive"], topics: [], editorialStatus: "live", archived: false, deprecated: false, hasSourceList: false, approvalStatus: "blocked_missing_metadata" },
  { slug: "two-week-wait", journey: ["trying-to-conceive"], topics: [], editorialStatus: "live", archived: false, deprecated: false, hasSourceList: false, approvalStatus: "blocked_missing_metadata" },
  { slug: "emotional-impact-of-ivf", journey: ["ivf","support"], topics: [], editorialStatus: "live", archived: false, deprecated: false, hasSourceList: true, approvalStatus: "blocked_missing_metadata" },
  { slug: "your-body-after-birth", journey: ["postpartum"], topics: [], editorialStatus: "live", archived: false, deprecated: false, hasSourceList: false, approvalStatus: "blocked_missing_metadata" },
  { slug: "baby-milestones-first-year", journey: ["first-year"], topics: [], editorialStatus: "live", archived: false, deprecated: false, hasSourceList: false, approvalStatus: "blocked_missing_metadata" },
  { slug: "what-to-buy-for-a-new-baby", journey: ["preparing-for-baby"], topics: [], editorialStatus: "live", archived: false, deprecated: false, hasSourceList: false, approvalStatus: "blocked_missing_metadata" },
  { slug: "perinatal-anxiety", journey: ["support","pregnancy","postpartum"], topics: [], editorialStatus: "live", archived: false, deprecated: false, hasSourceList: true, approvalStatus: "blocked_missing_metadata" },
  { slug: "writing-a-birth-plan", journey: ["preparing-for-baby","pregnancy"], topics: [], editorialStatus: "live", archived: false, deprecated: false, hasSourceList: false, approvalStatus: "blocked_missing_metadata" },
  { slug: "foods-to-avoid-in-pregnancy", journey: ["pregnancy"], topics: ["diet-and-exercise"], editorialStatus: "live", archived: false, deprecated: false, hasSourceList: true, approvalStatus: "blocked_missing_metadata" },
  { slug: "tests-and-scans-in-pregnancy", journey: ["pregnancy"], topics: ["health-and-safety"], editorialStatus: "live", archived: false, deprecated: false, hasSourceList: true, approvalStatus: "blocked_missing_metadata" },
  { slug: "vaccinations-in-pregnancy", journey: ["pregnancy"], topics: ["health-and-safety"], editorialStatus: "live", archived: false, deprecated: false, hasSourceList: true, approvalStatus: "blocked_missing_metadata" },
  { slug: "medicines-in-pregnancy", journey: ["pregnancy"], topics: ["health-and-safety"], editorialStatus: "live", archived: false, deprecated: false, hasSourceList: true, approvalStatus: "blocked_missing_metadata" },
  { slug: "hair-dye-and-beauty-treatments-in-pregnancy", journey: ["pregnancy"], topics: ["health-and-safety"], editorialStatus: "live", archived: false, deprecated: false, hasSourceList: true, approvalStatus: "blocked_missing_metadata" },
  { slug: "eating-well-in-pregnancy", journey: ["pregnancy"], topics: ["diet-and-exercise"], editorialStatus: "live", archived: false, deprecated: false, hasSourceList: true, approvalStatus: "blocked_missing_metadata" },
  { slug: "moving-your-body-in-pregnancy", journey: ["pregnancy"], topics: ["diet-and-exercise"], editorialStatus: "live", archived: false, deprecated: false, hasSourceList: true, approvalStatus: "blocked_missing_metadata" },
  { slug: "key-nutrients-in-pregnancy", journey: ["pregnancy"], topics: ["diet-and-exercise"], editorialStatus: "live", archived: false, deprecated: false, hasSourceList: true, approvalStatus: "blocked_missing_metadata" },
  { slug: "when-you-cant-face-food-in-pregnancy", journey: ["pregnancy"], topics: ["diet-and-exercise"], editorialStatus: "live", archived: false, deprecated: false, hasSourceList: true, approvalStatus: "blocked_missing_metadata" },
  { slug: "how-your-baby-develops-in-pregnancy", journey: ["pregnancy"], topics: ["baby"], editorialStatus: "live", archived: false, deprecated: false, hasSourceList: true, approvalStatus: "blocked_missing_metadata" },
  { slug: "twins-and-multiples-in-pregnancy", journey: ["pregnancy"], topics: ["baby"], editorialStatus: "live", archived: false, deprecated: false, hasSourceList: true, approvalStatus: "blocked_missing_metadata" },
  { slug: "the-space-your-baby-will-come-home-to", journey: ["pregnancy"], topics: ["preparing-for-baby"], editorialStatus: "live", archived: false, deprecated: false, hasSourceList: true, approvalStatus: "blocked_missing_metadata" },
  { slug: "sleep-in-pregnancy", journey: ["pregnancy"], topics: ["body"], editorialStatus: "live", archived: false, deprecated: false, hasSourceList: true, approvalStatus: "blocked_missing_metadata" },
  { slug: "signs-of-labour", journey: ["pregnancy"], topics: ["body"], editorialStatus: "live", archived: false, deprecated: false, hasSourceList: true, approvalStatus: "blocked_missing_metadata" },
  { slug: "stages-of-labour", journey: ["pregnancy"], topics: ["body"], editorialStatus: "live", archived: false, deprecated: false, hasSourceList: true, approvalStatus: "blocked_missing_metadata" },
  { slug: "when-to-go-in-for-labour", journey: ["pregnancy"], topics: ["body"], editorialStatus: "live", archived: false, deprecated: false, hasSourceList: true, approvalStatus: "blocked_missing_metadata" },
  { slug: "anxiety-in-pregnancy", journey: ["pregnancy","support"], topics: ["feelings"], editorialStatus: "live", archived: false, deprecated: false, hasSourceList: true, approvalStatus: "blocked_missing_metadata" },
  { slug: "pregnancy-after-loss", journey: ["pregnancy","support"], topics: ["feelings"], editorialStatus: "live", archived: false, deprecated: false, hasSourceList: true, approvalStatus: "blocked_missing_metadata" },
  { slug: "the-first-trimester-emotionally", journey: ["pregnancy","support"], topics: ["feelings"], editorialStatus: "live", archived: false, deprecated: false, hasSourceList: true, approvalStatus: "blocked_missing_metadata" },
  { slug: "when-the-joy-doesnt-arrive-yet", journey: ["pregnancy","support"], topics: ["feelings"], editorialStatus: "live", archived: false, deprecated: false, hasSourceList: true, approvalStatus: "blocked_missing_metadata" },
  { slug: "weight-changes-in-pregnancy", journey: ["pregnancy"], topics: ["health-and-safety"], editorialStatus: "live", archived: false, deprecated: false, hasSourceList: true, approvalStatus: "blocked_missing_metadata" },
  { slug: "hospital-bag-and-what-to-pack", journey: ["pregnancy"], topics: ["preparing-for-baby"], editorialStatus: "live", archived: false, deprecated: false, hasSourceList: true, approvalStatus: "blocked_missing_metadata" },
  { slug: "preparing-emotionally-for-birth", journey: ["pregnancy"], topics: ["feelings"], editorialStatus: "live", archived: false, deprecated: false, hasSourceList: true, approvalStatus: "blocked_missing_metadata" },
  { slug: "baby-movement-in-pregnancy", journey: ["pregnancy"], topics: ["baby"], editorialStatus: "live", archived: false, deprecated: false, hasSourceList: true, approvalStatus: "blocked_missing_metadata" },
  { slug: "pelvic-pain-in-pregnancy", journey: ["pregnancy"], topics: ["body"], editorialStatus: "live", archived: false, deprecated: false, hasSourceList: true, approvalStatus: "blocked_missing_metadata" },
  { slug: "round-ligament-pain", journey: ["pregnancy"], topics: ["body"], editorialStatus: "live", archived: false, deprecated: false, hasSourceList: true, approvalStatus: "blocked_missing_metadata" },
  { slug: "braxton-hicks-contractions", journey: ["pregnancy"], topics: ["body"], editorialStatus: "live", archived: false, deprecated: false, hasSourceList: true, approvalStatus: "blocked_missing_metadata" },
  { slug: "shortness-of-breath-in-pregnancy", journey: ["pregnancy"], topics: ["body"], editorialStatus: "live", archived: false, deprecated: false, hasSourceList: true, approvalStatus: "blocked_missing_metadata" },
  { slug: "swelling-in-pregnancy", journey: ["pregnancy"], topics: ["body"], editorialStatus: "live", archived: false, deprecated: false, hasSourceList: true, approvalStatus: "blocked_missing_metadata" },
  { slug: "heartburn-in-pregnancy", journey: ["pregnancy"], topics: ["body"], editorialStatus: "live", archived: false, deprecated: false, hasSourceList: true, approvalStatus: "blocked_missing_metadata" },
  { slug: "constipation-in-pregnancy", journey: ["pregnancy"], topics: ["body"], editorialStatus: "live", archived: false, deprecated: false, hasSourceList: true, approvalStatus: "blocked_missing_metadata" },
  { slug: "back-pain-in-pregnancy", journey: ["pregnancy"], topics: ["body"], editorialStatus: "live", archived: false, deprecated: false, hasSourceList: true, approvalStatus: "blocked_missing_metadata" },
  { slug: "anterior-placenta", journey: ["pregnancy"], topics: ["baby"], editorialStatus: "live", archived: false, deprecated: false, hasSourceList: true, approvalStatus: "blocked_missing_metadata" },
  { slug: "low-lying-placenta-in-pregnancy", journey: ["pregnancy"], topics: ["baby"], editorialStatus: "live", archived: false, deprecated: false, hasSourceList: true, approvalStatus: "blocked_missing_metadata" },
  { slug: "breech-baby", journey: ["pregnancy"], topics: ["baby"], editorialStatus: "live", archived: false, deprecated: false, hasSourceList: true, approvalStatus: "blocked_missing_metadata" },
  { slug: "reduced-movements-in-pregnancy", journey: ["pregnancy"], topics: ["baby"], editorialStatus: "live", archived: false, deprecated: false, hasSourceList: true, approvalStatus: "blocked_missing_metadata" },
  { slug: "baby-hiccups-in-the-womb", journey: ["pregnancy"], topics: ["baby"], editorialStatus: "live", archived: false, deprecated: false, hasSourceList: true, approvalStatus: "blocked_missing_metadata" },
  { slug: "measuring-big-or-small-in-pregnancy", journey: ["pregnancy"], topics: ["baby"], editorialStatus: "live", archived: false, deprecated: false, hasSourceList: true, approvalStatus: "blocked_missing_metadata" },
  { slug: "growth-scans-in-pregnancy", journey: ["pregnancy"], topics: ["baby"], editorialStatus: "live", archived: false, deprecated: false, hasSourceList: true, approvalStatus: "blocked_missing_metadata" },
  { slug: "cord-around-the-neck-in-pregnancy", journey: ["pregnancy"], topics: ["baby"], editorialStatus: "live", archived: false, deprecated: false, hasSourceList: true, approvalStatus: "blocked_missing_metadata" },
  { slug: "membrane-sweep", journey: ["pregnancy"], topics: ["body"], editorialStatus: "live", archived: false, deprecated: false, hasSourceList: true, approvalStatus: "blocked_missing_metadata" },
  { slug: "induction-of-labour", journey: ["pregnancy"], topics: ["body"], editorialStatus: "live", archived: false, deprecated: false, hasSourceList: true, approvalStatus: "blocked_missing_metadata" },
  { slug: "external-cephalic-version", journey: ["pregnancy"], topics: ["baby"], editorialStatus: "live", archived: false, deprecated: false, hasSourceList: true, approvalStatus: "blocked_missing_metadata" },
  { slug: "group-b-strep-in-pregnancy", journey: ["pregnancy"], topics: ["health-and-safety"], editorialStatus: "live", archived: false, deprecated: false, hasSourceList: true, approvalStatus: "blocked_missing_metadata" },
  { slug: "hand-expressing-colostrum", journey: ["pregnancy"], topics: ["preparing-for-baby"], editorialStatus: "live", archived: false, deprecated: false, hasSourceList: true, approvalStatus: "blocked_missing_metadata" },
  { slug: "the-36-week-appointment", journey: ["pregnancy"], topics: ["health-and-safety"], editorialStatus: "live", archived: false, deprecated: false, hasSourceList: true, approvalStatus: "blocked_missing_metadata" },
  { slug: "birth-preferences", journey: ["pregnancy","preparing-for-baby"], topics: ["preparing-for-baby"], editorialStatus: "live", archived: false, deprecated: false, hasSourceList: true, approvalStatus: "blocked_missing_metadata" },
  { slug: "what-happens-if-labour-doesnt-start", journey: ["pregnancy"], topics: ["body"], editorialStatus: "live", archived: false, deprecated: false, hasSourceList: true, approvalStatus: "blocked_missing_metadata" },
  { slug: "paracetamol-in-pregnancy", journey: ["pregnancy"], topics: ["health-and-safety"], editorialStatus: "live", archived: false, deprecated: false, hasSourceList: true, approvalStatus: "blocked_missing_metadata" },
  { slug: "antibiotics-in-pregnancy", journey: ["pregnancy"], topics: ["health-and-safety"], editorialStatus: "live", archived: false, deprecated: false, hasSourceList: true, approvalStatus: "blocked_missing_metadata" },
  { slug: "antacids-in-pregnancy", journey: ["pregnancy"], topics: ["health-and-safety"], editorialStatus: "live", archived: false, deprecated: false, hasSourceList: true, approvalStatus: "blocked_missing_metadata" },
  { slug: "laxatives-in-pregnancy", journey: ["pregnancy"], topics: ["health-and-safety"], editorialStatus: "live", archived: false, deprecated: false, hasSourceList: true, approvalStatus: "blocked_missing_metadata" },
  { slug: "hay-fever-in-pregnancy", journey: ["pregnancy"], topics: ["health-and-safety"], editorialStatus: "live", archived: false, deprecated: false, hasSourceList: true, approvalStatus: "blocked_missing_metadata" },
  { slug: "cold-and-flu-in-pregnancy", journey: ["pregnancy"], topics: ["health-and-safety"], editorialStatus: "live", archived: false, deprecated: false, hasSourceList: true, approvalStatus: "blocked_missing_metadata" },
  { slug: "uti-in-pregnancy", journey: ["pregnancy"], topics: ["health-and-safety"], editorialStatus: "live", archived: false, deprecated: false, hasSourceList: true, approvalStatus: "blocked_missing_metadata" },
  { slug: "thrush-in-pregnancy", journey: ["pregnancy"], topics: ["health-and-safety"], editorialStatus: "live", archived: false, deprecated: false, hasSourceList: true, approvalStatus: "blocked_missing_metadata" },
  { slug: "bleeding-in-early-pregnancy", journey: ["pregnancy"], topics: ["health-and-safety"], editorialStatus: "live", archived: false, deprecated: false, hasSourceList: true, approvalStatus: "blocked_missing_metadata" },
  { slug: "spotting-in-pregnancy", journey: ["pregnancy"], topics: ["health-and-safety"], editorialStatus: "live", archived: false, deprecated: false, hasSourceList: true, approvalStatus: "blocked_missing_metadata" },
  { slug: "discharge-in-pregnancy", journey: ["pregnancy"], topics: ["health-and-safety"], editorialStatus: "live", archived: false, deprecated: false, hasSourceList: true, approvalStatus: "blocked_missing_metadata" },
  { slug: "watery-discharge-in-pregnancy", journey: ["pregnancy"], topics: ["health-and-safety"], editorialStatus: "live", archived: false, deprecated: false, hasSourceList: true, approvalStatus: "blocked_missing_metadata" },
  { slug: "when-to-worry-about-cramps-in-pregnancy", journey: ["pregnancy"], topics: ["health-and-safety"], editorialStatus: "live", archived: false, deprecated: false, hasSourceList: true, approvalStatus: "blocked_missing_metadata" },
  { slug: "mucus-plug", journey: ["pregnancy"], topics: ["health-and-safety"], editorialStatus: "live", archived: false, deprecated: false, hasSourceList: true, approvalStatus: "blocked_missing_metadata" },
  { slug: "show-in-pregnancy", journey: ["pregnancy"], topics: ["health-and-safety"], editorialStatus: "live", archived: false, deprecated: false, hasSourceList: true, approvalStatus: "blocked_missing_metadata" },
  { slug: "leaking-fluid-in-pregnancy", journey: ["pregnancy"], topics: ["health-and-safety"], editorialStatus: "live", archived: false, deprecated: false, hasSourceList: true, approvalStatus: "blocked_missing_metadata" },
  { slug: "nipt-in-pregnancy", journey: ["pregnancy"], topics: ["health-and-safety"], editorialStatus: "live", archived: false, deprecated: false, hasSourceList: true, approvalStatus: "blocked_missing_metadata" },
  { slug: "combined-screening-test", journey: ["pregnancy"], topics: ["health-and-safety"], editorialStatus: "live", archived: false, deprecated: false, hasSourceList: true, approvalStatus: "blocked_missing_metadata" },
  { slug: "dating-scan", journey: ["pregnancy"], topics: ["health-and-safety"], editorialStatus: "live", archived: false, deprecated: false, hasSourceList: true, approvalStatus: "blocked_missing_metadata" },
  { slug: "20-week-anomaly-scan", journey: ["pregnancy"], topics: ["health-and-safety"], editorialStatus: "live", archived: false, deprecated: false, hasSourceList: true, approvalStatus: "blocked_missing_metadata" },
  { slug: "glucose-tolerance-test", journey: ["pregnancy"], topics: ["health-and-safety"], editorialStatus: "live", archived: false, deprecated: false, hasSourceList: true, approvalStatus: "blocked_missing_metadata" },
  { slug: "anti-d-injection-in-pregnancy", journey: ["pregnancy"], topics: ["health-and-safety"], editorialStatus: "live", archived: false, deprecated: false, hasSourceList: true, approvalStatus: "blocked_missing_metadata" },
  { slug: "what-happens-at-booking-appointment", journey: ["pregnancy"], topics: ["health-and-safety"], editorialStatus: "live", archived: false, deprecated: false, hasSourceList: true, approvalStatus: "blocked_missing_metadata" },
  { slug: "what-if-a-scan-shows-something-unexpected", journey: ["pregnancy"], topics: ["health-and-safety"], editorialStatus: "live", archived: false, deprecated: false, hasSourceList: true, approvalStatus: "blocked_missing_metadata" },
  { slug: "ovulation-signs", journey: ["trying-to-conceive"], topics: [], editorialStatus: "live", archived: false, deprecated: false, hasSourceList: false, approvalStatus: "blocked_missing_metadata" },
  { slug: "fertile-window", journey: ["trying-to-conceive"], topics: [], editorialStatus: "live", archived: false, deprecated: false, hasSourceList: false, approvalStatus: "blocked_missing_metadata" },
  { slug: "how-long-implantation-takes", journey: ["trying-to-conceive"], topics: [], editorialStatus: "live", archived: false, deprecated: false, hasSourceList: false, approvalStatus: "blocked_missing_metadata" },
  { slug: "when-to-take-a-pregnancy-test", journey: ["trying-to-conceive"], topics: [], editorialStatus: "live", archived: false, deprecated: false, hasSourceList: false, approvalStatus: "blocked_missing_metadata" },
  { slug: "faint-positive-pregnancy-test", journey: ["trying-to-conceive"], topics: [], editorialStatus: "live", archived: false, deprecated: false, hasSourceList: false, approvalStatus: "blocked_missing_metadata" },
  { slug: "chemical-pregnancy", journey: ["trying-to-conceive","support"], topics: [], editorialStatus: "live", archived: false, deprecated: false, hasSourceList: false, approvalStatus: "blocked_missing_metadata" },
  { slug: "trying-again-after-miscarriage", journey: ["trying-to-conceive","support"], topics: [], editorialStatus: "live", archived: false, deprecated: false, hasSourceList: false, approvalStatus: "blocked_missing_metadata" },
  { slug: "can-you-get-pregnant-on-your-period", journey: ["trying-to-conceive"], topics: [], editorialStatus: "live", archived: false, deprecated: false, hasSourceList: false, approvalStatus: "blocked_missing_metadata" },
  { slug: "how-long-to-try-before-getting-help", journey: ["trying-to-conceive"], topics: [], editorialStatus: "live", archived: false, deprecated: false, hasSourceList: true, approvalStatus: "blocked_missing_metadata" },
  { slug: "pcos-and-trying-to-conceive", journey: ["trying-to-conceive"], topics: [], editorialStatus: "live", archived: false, deprecated: false, hasSourceList: true, approvalStatus: "blocked_missing_metadata" },
  { slug: "endometriosis-and-trying-to-conceive", journey: ["trying-to-conceive"], topics: [], editorialStatus: "live", archived: false, deprecated: false, hasSourceList: true, approvalStatus: "blocked_missing_metadata" },
  { slug: "irregular-periods-and-trying-to-conceive", journey: ["trying-to-conceive"], topics: [], editorialStatus: "live", archived: false, deprecated: false, hasSourceList: true, approvalStatus: "blocked_missing_metadata" },
  { slug: "fertility-tests-for-women", journey: ["trying-to-conceive"], topics: [], editorialStatus: "live", archived: false, deprecated: false, hasSourceList: true, approvalStatus: "blocked_missing_metadata" },
  { slug: "fertility-tests-for-men", journey: ["trying-to-conceive"], topics: [], editorialStatus: "live", archived: false, deprecated: false, hasSourceList: true, approvalStatus: "blocked_missing_metadata" },
  { slug: "what-happens-at-a-fertility-appointment", journey: ["trying-to-conceive"], topics: [], editorialStatus: "live", archived: false, deprecated: false, hasSourceList: true, approvalStatus: "blocked_missing_metadata" },
  { slug: "amh-test-explained", journey: ["trying-to-conceive"], topics: [], editorialStatus: "live", archived: false, deprecated: false, hasSourceList: true, approvalStatus: "blocked_missing_metadata" },
  { slug: "how-to-know-when-you-are-ovulating", journey: ["trying-to-conceive"], topics: [], editorialStatus: "unknown", archived: false, deprecated: false, hasSourceList: true, approvalStatus: "blocked_missing_metadata" },
  { slug: "understanding-your-fertile-window", journey: ["trying-to-conceive"], topics: [], editorialStatus: "unknown", archived: false, deprecated: false, hasSourceList: true, approvalStatus: "blocked_missing_metadata" },
  { slug: "using-ovulation-tests", journey: ["trying-to-conceive"], topics: [], editorialStatus: "unknown", archived: false, deprecated: false, hasSourceList: true, approvalStatus: "blocked_missing_metadata" },
  { slug: "cervical-mucus-and-fertility", journey: ["trying-to-conceive"], topics: [], editorialStatus: "unknown", archived: false, deprecated: false, hasSourceList: true, approvalStatus: "blocked_missing_metadata" },
  { slug: "late-ovulation-and-ttc", journey: ["trying-to-conceive"], topics: [], editorialStatus: "unknown", archived: false, deprecated: false, hasSourceList: true, approvalStatus: "blocked_missing_metadata" },
  { slug: "when-ovulation-is-hard-to-predict", journey: ["trying-to-conceive"], topics: [], editorialStatus: "unknown", archived: false, deprecated: false, hasSourceList: true, approvalStatus: "blocked_missing_metadata" },
  { slug: "timing-sex-when-trying-to-conceive", journey: ["trying-to-conceive"], topics: [], editorialStatus: "unknown", archived: false, deprecated: false, hasSourceList: true, approvalStatus: "blocked_missing_metadata" },
  { slug: "basal-body-temperature-tracking", journey: ["trying-to-conceive"], topics: [], editorialStatus: "unknown", archived: false, deprecated: false, hasSourceList: true, approvalStatus: "blocked_missing_metadata" },
  { slug: "what-to-do-before-trying-to-conceive", journey: ["trying-to-conceive"], topics: [], editorialStatus: "unknown", archived: false, deprecated: false, hasSourceList: true, approvalStatus: "blocked_missing_metadata" },
  { slug: "folic-acid-before-pregnancy", journey: ["trying-to-conceive"], topics: [], editorialStatus: "unknown", archived: false, deprecated: false, hasSourceList: true, approvalStatus: "blocked_missing_metadata" },
  { slug: "preconception-vitamins", journey: ["trying-to-conceive"], topics: [], editorialStatus: "unknown", archived: false, deprecated: false, hasSourceList: true, approvalStatus: "blocked_missing_metadata" },
  { slug: "preconception-gp-appointment", journey: ["trying-to-conceive"], topics: [], editorialStatus: "unknown", archived: false, deprecated: false, hasSourceList: true, approvalStatus: "blocked_missing_metadata" },
  { slug: "stopping-contraception-when-ttc", journey: ["trying-to-conceive"], topics: [], editorialStatus: "unknown", archived: false, deprecated: false, hasSourceList: true, approvalStatus: "blocked_missing_metadata" },
  { slug: "medication-review-before-pregnancy", journey: ["trying-to-conceive"], topics: [], editorialStatus: "unknown", archived: false, deprecated: false, hasSourceList: true, approvalStatus: "blocked_missing_metadata" },
  { slug: "lifestyle-before-pregnancy", journey: ["trying-to-conceive"], topics: [], editorialStatus: "unknown", archived: false, deprecated: false, hasSourceList: true, approvalStatus: "blocked_missing_metadata" },
  { slug: "mental-wellbeing-before-pregnancy", journey: ["trying-to-conceive"], topics: [], editorialStatus: "unknown", archived: false, deprecated: false, hasSourceList: true, approvalStatus: "blocked_missing_metadata" },
  { slug: "partner-health-before-pregnancy", journey: ["trying-to-conceive"], topics: [], editorialStatus: "unknown", archived: false, deprecated: false, hasSourceList: true, approvalStatus: "blocked_missing_metadata" },
  { slug: "sperm-health-basics", journey: ["trying-to-conceive"], topics: [], editorialStatus: "unknown", archived: false, deprecated: false, hasSourceList: true, approvalStatus: "blocked_missing_metadata" },
  { slug: "when-to-ask-for-fertility-help", journey: ["trying-to-conceive"], topics: [], editorialStatus: "unknown", archived: false, deprecated: false, hasSourceList: true, approvalStatus: "blocked_missing_metadata" },
  { slug: "unexplained-fertility-concerns", journey: ["trying-to-conceive"], topics: [], editorialStatus: "unknown", archived: false, deprecated: false, hasSourceList: true, approvalStatus: "blocked_missing_metadata" },
  { slug: "age-and-trying-to-conceive", journey: ["trying-to-conceive"], topics: [], editorialStatus: "unknown", archived: false, deprecated: false, hasSourceList: true, approvalStatus: "blocked_missing_metadata" },
  { slug: "male-fertility-when-trying-to-conceive", journey: ["trying-to-conceive"], topics: [], editorialStatus: "unknown", archived: false, deprecated: false, hasSourceList: true, approvalStatus: "blocked_missing_metadata" },
  { slug: "moving-from-ttc-to-ivf", journey: ["trying-to-conceive"], topics: [], editorialStatus: "unknown", archived: false, deprecated: false, hasSourceList: true, approvalStatus: "blocked_missing_metadata" },
  { slug: "caffeine-in-pregnancy", journey: ["pregnancy"], topics: ["diet-and-exercise"], editorialStatus: "unknown", archived: false, deprecated: false, hasSourceList: true, approvalStatus: "blocked_missing_metadata" },
  { slug: "hydration-in-pregnancy", journey: ["pregnancy"], topics: ["diet-and-exercise"], editorialStatus: "unknown", archived: false, deprecated: false, hasSourceList: true, approvalStatus: "blocked_missing_metadata" },
  { slug: "cravings-and-aversions-in-pregnancy", journey: ["pregnancy"], topics: ["diet-and-exercise"], editorialStatus: "unknown", archived: false, deprecated: false, hasSourceList: true, approvalStatus: "blocked_missing_metadata" },
  { slug: "pelvic-floor-exercises-in-pregnancy", journey: ["pregnancy"], topics: ["diet-and-exercise"], editorialStatus: "unknown", archived: false, deprecated: false, hasSourceList: true, approvalStatus: "blocked_missing_metadata" },
  { slug: "exercise-safety-by-trimester", journey: ["pregnancy"], topics: ["diet-and-exercise"], editorialStatus: "unknown", archived: false, deprecated: false, hasSourceList: true, approvalStatus: "blocked_missing_metadata" },
  { slug: "safe-sleep-basics", journey: ["pregnancy"], topics: ["preparing-for-baby"], editorialStatus: "unknown", archived: false, deprecated: false, hasSourceList: true, approvalStatus: "blocked_missing_metadata" },
  { slug: "car-seat-basics", journey: ["pregnancy"], topics: ["preparing-for-baby"], editorialStatus: "unknown", archived: false, deprecated: false, hasSourceList: true, approvalStatus: "blocked_missing_metadata" },
  { slug: "baby-clothes-and-newborn-essentials", journey: ["pregnancy"], topics: ["preparing-for-baby"], editorialStatus: "unknown", archived: false, deprecated: false, hasSourceList: true, approvalStatus: "blocked_missing_metadata" },
  { slug: "preparing-siblings-for-a-new-baby", journey: ["pregnancy"], topics: ["preparing-for-baby"], editorialStatus: "unknown", archived: false, deprecated: false, hasSourceList: true, approvalStatus: "blocked_missing_metadata" },
  { slug: "maternity-leave-planning", journey: ["pregnancy"], topics: ["preparing-for-baby"], editorialStatus: "unknown", archived: false, deprecated: false, hasSourceList: true, approvalStatus: "blocked_missing_metadata" },
  { slug: "testing-too-early", journey: ["trying-to-conceive"], topics: [], editorialStatus: "unknown", archived: false, deprecated: false, hasSourceList: true, approvalStatus: "blocked_missing_metadata" },
  { slug: "negative-test-but-no-period", journey: ["trying-to-conceive"], topics: [], editorialStatus: "unknown", archived: false, deprecated: false, hasSourceList: true, approvalStatus: "blocked_missing_metadata" },
  { slug: "evaporation-line-or-faint-positive", journey: ["trying-to-conceive"], topics: [], editorialStatus: "unknown", archived: false, deprecated: false, hasSourceList: true, approvalStatus: "blocked_missing_metadata" },
  { slug: "two-week-wait-symptoms", journey: ["trying-to-conceive"], topics: [], editorialStatus: "unknown", archived: false, deprecated: false, hasSourceList: true, approvalStatus: "blocked_missing_metadata" },
  { slug: "spotting-during-the-two-week-wait", journey: ["trying-to-conceive"], topics: [], editorialStatus: "unknown", archived: false, deprecated: false, hasSourceList: true, approvalStatus: "blocked_missing_metadata" },
  { slug: "coping-with-the-two-week-wait", journey: ["trying-to-conceive","support"], topics: [], editorialStatus: "unknown", archived: false, deprecated: false, hasSourceList: true, approvalStatus: "blocked_missing_metadata" },
  { slug: "tracking-without-overthinking", journey: ["trying-to-conceive"], topics: [], editorialStatus: "unknown", archived: false, deprecated: false, hasSourceList: true, approvalStatus: "blocked_missing_metadata" },
  { slug: "thyroid-and-fertility", journey: ["trying-to-conceive"], topics: [], editorialStatus: "unknown", archived: false, deprecated: false, hasSourceList: true, approvalStatus: "blocked_missing_metadata" },
  { slug: "ttc-in-your-30s", journey: ["trying-to-conceive"], topics: [], editorialStatus: "unknown", archived: false, deprecated: false, hasSourceList: true, approvalStatus: "blocked_missing_metadata" },
  { slug: "ttc-after-35", journey: ["trying-to-conceive"], topics: [], editorialStatus: "unknown", archived: false, deprecated: false, hasSourceList: true, approvalStatus: "blocked_missing_metadata" },
  { slug: "emotional-pressure-of-age-when-ttc", journey: ["trying-to-conceive","support"], topics: [], editorialStatus: "unknown", archived: false, deprecated: false, hasSourceList: true, approvalStatus: "blocked_missing_metadata" },
  { slug: "partner-support-when-ttc", journey: ["trying-to-conceive","support"], topics: [], editorialStatus: "unknown", archived: false, deprecated: false, hasSourceList: true, approvalStatus: "blocked_missing_metadata" },
  { slug: "preparing-for-another-baby", journey: ["family"], topics: ["growing-families"], editorialStatus: "draft", archived: false, deprecated: false, hasSourceList: false, approvalStatus: "blocked_draft" },
  { slug: "helping-your-child-adjust-to-a-new-sibling", journey: ["family"], topics: ["growing-families"], editorialStatus: "draft", archived: false, deprecated: false, hasSourceList: false, approvalStatus: "blocked_draft" },
  { slug: "setting-boundaries-with-grandparents", journey: ["family"], topics: ["relationships"], editorialStatus: "draft", archived: false, deprecated: false, hasSourceList: false, approvalStatus: "blocked_draft" },
  { slug: "sharing-the-mental-load", journey: ["family"], topics: ["relationships"], editorialStatus: "draft", archived: false, deprecated: false, hasSourceList: false, approvalStatus: "blocked_draft" },
  { slug: "building-family-routines", journey: ["family"], topics: ["family-basics"], editorialStatus: "draft", archived: false, deprecated: false, hasSourceList: false, approvalStatus: "blocked_draft" },
  { slug: "managing-childcare-costs", journey: ["family"], topics: ["family-basics"], editorialStatus: "draft", archived: false, deprecated: false, hasSourceList: true, approvalStatus: "blocked_draft" },
  { slug: "making-your-home-safer", journey: ["family"], topics: ["health-safety"], editorialStatus: "draft", archived: false, deprecated: false, hasSourceList: true, approvalStatus: "blocked_draft" },
  { slug: "when-to-ask-for-help", journey: ["family"], topics: ["health-safety"], editorialStatus: "draft", archived: false, deprecated: false, hasSourceList: true, approvalStatus: "blocked_draft" },
  { slug: "travelling-with-young-children", journey: ["family"], topics: ["travel-days-out"], editorialStatus: "draft", archived: false, deprecated: false, hasSourceList: false, approvalStatus: "blocked_draft" },
  { slug: "making-car-journeys-calmer", journey: ["family"], topics: ["travel-days-out"], editorialStatus: "draft", archived: false, deprecated: false, hasSourceList: false, approvalStatus: "blocked_draft" },
  { slug: "building-family-traditions", journey: ["family"], topics: ["play-connection"], editorialStatus: "draft", archived: false, deprecated: false, hasSourceList: false, approvalStatus: "blocked_draft" },
  { slug: "screen-time-as-a-family", journey: ["family"], topics: ["play-connection"], editorialStatus: "draft", archived: false, deprecated: false, hasSourceList: false, approvalStatus: "blocked_draft" },
  { slug: "second-time-parenting", journey: ["family"], topics: ["growing-families"], editorialStatus: "live", archived: false, deprecated: false, hasSourceList: false, approvalStatus: "blocked_missing_metadata" },
  { slug: "staying-connected-as-parents", journey: ["family"], topics: ["relationships"], editorialStatus: "live", archived: false, deprecated: false, hasSourceList: false, approvalStatus: "blocked_missing_metadata" },
  { slug: "calmer-evenings-after-busy-days", journey: ["family"], topics: ["family-basics"], editorialStatus: "live", archived: false, deprecated: false, hasSourceList: false, approvalStatus: "blocked_missing_metadata" },
  { slug: "family-sick-days-at-home", journey: ["family"], topics: ["health-safety"], editorialStatus: "live", archived: false, deprecated: false, hasSourceList: true, approvalStatus: "blocked_missing_metadata" },
  { slug: "planning-family-days-out", journey: ["family"], topics: ["travel-days-out"], editorialStatus: "live", archived: false, deprecated: false, hasSourceList: false, approvalStatus: "blocked_missing_metadata" },
  { slug: "simple-family-play-ideas", journey: ["family"], topics: ["play-connection"], editorialStatus: "live", archived: false, deprecated: false, hasSourceList: false, approvalStatus: "blocked_missing_metadata" },
  { slug: "newborn-feeding-rhythms", journey: ["first-year"], topics: ["feeding"], editorialStatus: "draft", archived: false, deprecated: false, hasSourceList: true, approvalStatus: "blocked_draft" },
  { slug: "bottle-and-breastfeeding-questions", journey: ["first-year"], topics: ["feeding"], editorialStatus: "draft", archived: false, deprecated: false, hasSourceList: true, approvalStatus: "blocked_draft" },
  { slug: "newborn-sleep-expectations", journey: ["first-year"], topics: ["sleep"], editorialStatus: "draft", archived: false, deprecated: false, hasSourceList: true, approvalStatus: "blocked_draft" },
  { slug: "helping-your-baby-settle", journey: ["first-year"], topics: ["sleep"], editorialStatus: "draft", archived: false, deprecated: false, hasSourceList: true, approvalStatus: "blocked_draft" },
  { slug: "when-sleep-suddenly-changes", journey: ["first-year"], topics: ["sleep"], editorialStatus: "draft", archived: false, deprecated: false, hasSourceList: true, approvalStatus: "blocked_draft" },
  { slug: "baby-development-in-the-first-year", journey: ["first-year"], topics: ["development"], editorialStatus: "draft", archived: false, deprecated: false, hasSourceList: true, approvalStatus: "blocked_draft" },
  { slug: "when-milestones-feel-uneven", journey: ["first-year"], topics: ["development"], editorialStatus: "draft", archived: false, deprecated: false, hasSourceList: true, approvalStatus: "blocked_draft" },
  { slug: "baby-care-basics", journey: ["first-year"], topics: ["care-and-safety"], editorialStatus: "draft", archived: false, deprecated: false, hasSourceList: true, approvalStatus: "blocked_draft" },
  { slug: "safe-sleep-and-home-safety", journey: ["first-year"], topics: ["care-and-safety"], editorialStatus: "draft", archived: false, deprecated: false, hasSourceList: true, approvalStatus: "blocked_draft" },
  { slug: "healing-after-birth", journey: ["first-year"], topics: ["postpartum-recovery"], editorialStatus: "draft", archived: false, deprecated: false, hasSourceList: true, approvalStatus: "blocked_draft" },
  { slug: "what-recovery-can-feel-like", journey: ["first-year"], topics: ["postpartum-recovery"], editorialStatus: "draft", archived: false, deprecated: false, hasSourceList: true, approvalStatus: "blocked_draft" },
  { slug: "feeling-like-yourself-again", journey: ["first-year"], topics: ["emotional-wellbeing"], editorialStatus: "draft", archived: false, deprecated: false, hasSourceList: true, approvalStatus: "blocked_draft" },
  { slug: "when-parenthood-feels-heavy", journey: ["first-year"], topics: ["emotional-wellbeing"], editorialStatus: "draft", archived: false, deprecated: false, hasSourceList: true, approvalStatus: "blocked_draft" },
  { slug: "body-changes-after-birth", journey: ["first-year"], topics: ["body-and-hormones"], editorialStatus: "draft", archived: false, deprecated: false, hasSourceList: true, approvalStatus: "blocked_draft" },
  { slug: "hormones-sweat-and-hair-loss", journey: ["first-year"], topics: ["body-and-hormones"], editorialStatus: "draft", archived: false, deprecated: false, hasSourceList: true, approvalStatus: "blocked_draft" },
  { slug: "postnatal-checks-and-appointments", journey: ["first-year"], topics: ["checkups-and-warning-signs"], editorialStatus: "draft", archived: false, deprecated: false, hasSourceList: true, approvalStatus: "blocked_draft" },
  { slug: "when-to-ask-for-help-after-birth", journey: ["first-year"], topics: ["checkups-and-warning-signs"], editorialStatus: "draft", archived: false, deprecated: false, hasSourceList: true, approvalStatus: "blocked_draft" },
  { slug: "what-toddler-development-can-look-like", journey: ["toddler"], topics: ["development-milestones"], editorialStatus: "draft", archived: false, deprecated: false, hasSourceList: true, approvalStatus: "blocked_draft" },
  { slug: "when-milestones-feel-different", journey: ["toddler"], topics: ["development-milestones"], editorialStatus: "draft", archived: false, deprecated: false, hasSourceList: true, approvalStatus: "blocked_draft" },
  { slug: "understanding-toddler-tantrums", journey: ["toddler"], topics: ["behaviour-emotions"], editorialStatus: "draft", archived: false, deprecated: false, hasSourceList: true, approvalStatus: "blocked_draft" },
  { slug: "helping-your-toddler-with-big-feelings", journey: ["toddler"], topics: ["behaviour-emotions"], editorialStatus: "draft", archived: false, deprecated: false, hasSourceList: true, approvalStatus: "blocked_draft" },
  { slug: "supporting-toddler-speech-at-home", journey: ["toddler"], topics: ["speech-language"], editorialStatus: "draft", archived: false, deprecated: false, hasSourceList: true, approvalStatus: "blocked_draft" },
  { slug: "when-to-ask-about-speech-delay", journey: ["toddler"], topics: ["speech-language"], editorialStatus: "draft", archived: false, deprecated: false, hasSourceList: true, approvalStatus: "blocked_draft" },
  { slug: "toddler-sleep-rhythms", journey: ["toddler"], topics: ["sleep"], editorialStatus: "draft", archived: false, deprecated: false, hasSourceList: true, approvalStatus: "blocked_draft" },
  { slug: "bedtime-battles-and-night-waking", journey: ["toddler"], topics: ["sleep"], editorialStatus: "draft", archived: false, deprecated: false, hasSourceList: true, approvalStatus: "blocked_draft" },
  { slug: "picky-eating-in-toddlers", journey: ["toddler"], topics: ["food-feeding"], editorialStatus: "draft", archived: false, deprecated: false, hasSourceList: true, approvalStatus: "blocked_draft" },
  { slug: "making-mealtimes-feel-calmer", journey: ["toddler"], topics: ["food-feeding"], editorialStatus: "draft", archived: false, deprecated: false, hasSourceList: true, approvalStatus: "blocked_draft" },
  { slug: "signs-your-child-may-be-ready-for-potty-training", journey: ["toddler"], topics: ["potty-learning"], editorialStatus: "draft", archived: false, deprecated: false, hasSourceList: true, approvalStatus: "blocked_draft" },
  { slug: "potty-training-without-pressure", journey: ["toddler"], topics: ["potty-learning"], editorialStatus: "draft", archived: false, deprecated: false, hasSourceList: true, approvalStatus: "blocked_draft" },
  { slug: "toddler-home-safety", journey: ["toddler"], topics: ["health-safety"], editorialStatus: "draft", archived: false, deprecated: false, hasSourceList: true, approvalStatus: "blocked_draft" },
  { slug: "when-to-call-the-gp", journey: ["toddler"], topics: ["health-safety"], editorialStatus: "draft", archived: false, deprecated: false, hasSourceList: true, approvalStatus: "blocked_draft" },
  { slug: "simple-play-ideas-for-toddlers", journey: ["toddler"], topics: ["play-connection"], editorialStatus: "draft", archived: false, deprecated: false, hasSourceList: true, approvalStatus: "blocked_draft" },
  { slug: "building-connection-through-everyday-play", journey: ["toddler"], topics: ["play-connection"], editorialStatus: "draft", archived: false, deprecated: false, hasSourceList: true, approvalStatus: "blocked_draft" },

  // Phase 33 — runtime preview records held for human review (not approved).
  { slug: "itching-in-pregnancy", journey: ["pregnancy"], topics: ["body"], editorialStatus: "draft", archived: false, deprecated: false, hasSourceList: true, approvalStatus: "blocked_draft" },
  { slug: "caesarean-birth", journey: ["pregnancy"], topics: ["preparing-for-baby"], editorialStatus: "draft", archived: false, deprecated: false, hasSourceList: true, approvalStatus: "blocked_draft" },
  { slug: "gestational-diabetes", journey: ["pregnancy"], topics: ["health-and-safety"], editorialStatus: "draft", archived: false, deprecated: false, hasSourceList: true, approvalStatus: "blocked_draft" },
  { slug: "diarrhoea-and-tummy-bugs-in-pregnancy", journey: ["pregnancy"], topics: ["safety-and-support"], editorialStatus: "draft", archived: false, deprecated: false, hasSourceList: true, approvalStatus: "blocked_draft" },
  { slug: "leg-cramps-in-pregnancy", journey: ["pregnancy"], topics: ["common-symptoms"], editorialStatus: "draft", archived: false, deprecated: false, hasSourceList: true, approvalStatus: "blocked_draft" },
  { slug: "hcg-levels-explained", journey: ["pregnancy","trying-to-conceive"], topics: ["safety-and-support"], editorialStatus: "draft", archived: false, deprecated: false, hasSourceList: true, approvalStatus: "blocked_draft" },
  { slug: "sex-during-pregnancy", journey: ["pregnancy"], topics: ["relationships-and-feelings"], editorialStatus: "draft", archived: false, deprecated: false, hasSourceList: true, approvalStatus: "blocked_draft" },
  { slug: "dizziness-and-feeling-faint-in-pregnancy", journey: ["pregnancy"], topics: ["common-symptoms"], editorialStatus: "draft", archived: false, deprecated: false, hasSourceList: true, approvalStatus: "blocked_draft" },
  { slug: "teething", journey: ["first-year"], topics: ["care-and-safety"], editorialStatus: "draft", archived: false, deprecated: false, hasSourceList: true, approvalStatus: "blocked_draft" },
  { slug: "colic-and-evening-crying", journey: ["first-year"], topics: ["care-and-safety"], editorialStatus: "draft", archived: false, deprecated: false, hasSourceList: true, approvalStatus: "blocked_draft" },
  { slug: "introducing-solid-foods", journey: ["first-year"], topics: ["feeding"], editorialStatus: "draft", archived: false, deprecated: false, hasSourceList: true, approvalStatus: "blocked_draft" },
  { slug: "stitches-tears-and-perineal-healing", journey: ["first-year"], topics: ["postpartum-recovery"], editorialStatus: "draft", archived: false, deprecated: false, hasSourceList: true, approvalStatus: "blocked_draft" },
  { slug: "separated-tummy-muscles", journey: ["first-year"], topics: ["body-and-hormones"], editorialStatus: "draft", archived: false, deprecated: false, hasSourceList: true, approvalStatus: "blocked_draft" },
  { slug: "sex-and-intimacy-after-birth", journey: ["first-year"], topics: ["body-and-hormones"], editorialStatus: "draft", archived: false, deprecated: false, hasSourceList: true, approvalStatus: "blocked_draft" },
  { slug: "newborn-quirks-and-reflexes", journey: ["first-year"], topics: ["care-and-safety"], editorialStatus: "draft", archived: false, deprecated: false, hasSourceList: true, approvalStatus: "blocked_draft" },
  { slug: "newborn-skin-spots-and-marks", journey: ["first-year"], topics: ["care-and-safety"], editorialStatus: "draft", archived: false, deprecated: false, hasSourceList: true, approvalStatus: "blocked_draft" },
  { slug: "common-illnesses-in-the-first-year", journey: ["first-year"], topics: ["checkups-and-warning-signs"], editorialStatus: "draft", archived: false, deprecated: false, hasSourceList: true, approvalStatus: "blocked_draft" },
];

const BY_SLUG: ReadonlyMap<string, ArticleGroundingRecord> = new Map(
  ARTICLE_GROUNDING_REGISTRY.map((record) => [record.slug, record]),
);

/** Returns the governance record for a slug, or undefined when uncovered. */
export const getArticleGroundingRecord = (
  slug: string,
): ArticleGroundingRecord | undefined => BY_SLUG.get(slug);

/** Every slug the registry explicitly covers. */
export const listArticleGroundingSlugs = (): string[] =>
  ARTICLE_GROUNDING_REGISTRY.map((record) => record.slug);
